title: Rob Eden
email: robeden1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rob Eden: twiddler of bits, pixels and sawdust
baseurl: "" # the subpath of your site, e.g. /blog
url: http://robeden.com
twitter_username: robeden
github_username:  robeden
bitbucket_username:  robeden

# Build settings
markdown: kramdown
#theme: jekyll-simple-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - .well-known
  
 
clicky_analytics: 101097574 
#google_analytics: UA-89544639-1
disqus_shortname: robeden


excerpt_separator: <!--more-->
